node scripts/migrate-isomer-next.cjs mti-corp
node scripts/migrate-isomer-next.cjs moh-corp-next
node scripts/migrate-isomer-next.cjs moh-hpp-next
node scripts/migrate-isomer-next.cjs moh-healthwatch-next
node scripts/migrate-isomer-next.cjs moh-hcsa-next
node scripts/migrate-isomer-next.cjs moh-ifeelyoung-next
node scripts/migrate-isomer-next.cjs moh-biosafety-next
node scripts/migrate-isomer-next.cjs moh-dc-next
node scripts/migrate-isomer-next.cjs moh-prepare-next
node scripts/migrate-isomer-next.cjs agc-corp-next
node scripts/migrate-isomer-next.cjs agc-lsc-next
node scripts/migrate-isomer-next.cjs moh-spc-next
node scripts/migrate-isomer-next.cjs moh-tcmpb-next
